import { Project, ProjectItem } from '@kms/shared'
import { generateItemCommand } from './items'

export function generatePackMcmeta(projectName: string): string {
  return JSON.stringify({
    pack: {
      pack_format: 41,
      description: `KidModStudio: ${projectName}`
    }
  }, null, 2)
}

export function generateGiveFunction(item: ProjectItem): string {
  const command = generateItemCommand(item)
  return `# ${item.name}\n# Generated by KidModStudio\n${command}\n`
}

function sanitizeFileName(name: string): string {
  return name
    .toLowerCase()
    .replace(/ä/g, 'a').replace(/ö/g, 'o').replace(/ü/g, 'u').replace(/ß/g, 'ss')
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
}

export function generateDatapackStructure(project: Project): Record<string, string> {
  const files: Record<string, string> = {}

  // pack.mcmeta
  files['pack.mcmeta'] = generatePackMcmeta(project.name)

  // Individual give functions
  const functionCalls: string[] = []

  for (const item of project.items) {
    const fileName = sanitizeFileName(item.name)
    const path = `data/kidmod/function/give/${fileName}.mcfunction`
    files[path] = generateGiveFunction(item)
    functionCalls.push(`function kidmod:give/${fileName}`)
  }

  // give_all function
  files['data/kidmod/function/give_all.mcfunction'] =
    `# Give all items from ${project.name}\n# Generated by KidModStudio\n\n${functionCalls.join('\n')}\n`

  return files
}

export async function generateDatapack(project: Project, outputPath: string): Promise<void> {
  const { mkdir, writeFile } = await import('fs/promises')
  const { join, dirname } = await import('path')

  const files = generateDatapackStructure(project)

  for (const [relativePath, content] of Object.entries(files)) {
    const fullPath = join(outputPath, relativePath)
    await mkdir(dirname(fullPath), { recursive: true })
    await writeFile(fullPath, content, 'utf-8')
  }
}
